services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"  # For OAuth callback
    command: tail -f /dev/null  # Keep container running
